meetballs/urls.py
from django.contrib import admin
from django.urls import path, include
from meet_balls_app import views as app_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = (
    [
        path("admin/", admin.site.urls),
        path("", app_views.home, name="home"),
        path("game-events/", include("game_event.urls")),
        path("login/", app_views.loginUser, name="loginUser"),
        path("logout/", app_views.logoutUser, name="logoutUser"),
        path("register/", app_views.registerUser, name="registerUser"),
        path("profile/<id>/", app_views.profile, name="profile"),
        path("edit-profile/", app_views.edit_profile, name="edit profile"),
        path('notifications/', app_views.notifications, name='notifications'),
    ]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

meet_balls_app/models.py
# from django.db import models

# Create your models here.

notification/models.py
from django.db import models
from django.utils import timezone
from player.models import Player


class NotificationType(models.TextChoices):
    WEBSITE = "website", "Website"
    EVENT = "game-event", "Game-Event"
    CHAT = "chat", "Chat"


class Notification(models.Model):
    player = models.ForeignKey(Player, on_delete=models.CASCADE)
    sent_time = models.DateTimeField(default=timezone.now)
    message = models.TextField(null=True, blank=True)
    notification_type = models.CharField(
        max_length=100,
        choices=NotificationType.choices,
        default=NotificationType.WEBSITE,
    )
    is_read = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.notification_type} - {self.message}"

player/models.py
from django.contrib.auth.models import User
from django.db import models
import datetime
from django.core.exceptions import ValidationError
from django.utils import timezone


class BallGame(models.TextChoices):
    Soccer = 'Soccer', 'Soccer'
    Basketball = 'Basketball', 'Basketball'
    Volleyball = 'Volleyball', 'Volleyball'
    Baseball = 'Baseball', 'Baseball'
    Tennis = 'Tennis', 'Tennis'
    Rugby = 'Rugby', 'Rugby'
    Golf = 'Golf', 'Golf'
    Cricket = 'Cricket', 'Cricket'
    Handball = 'Handball', 'Handball'


def user_directory_path(instance, filename):
    return 'user_{0}/{1}'.format(instance.user.id, filename)


class Player(models.Model):
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        primary_key=True)
    birth_date = models.DateField()
    favorite_ball_game = models.CharField(
        max_length=100,
        choices=BallGame.choices)
    profile_pic = models.ImageField(default='default-profile-pic.png', upload_to=user_directory_path)

    @staticmethod
    def create(username, password, birth_date, favorite_ball_game):
        player = Player(user=User.objects.create_user(
                    username=username,
                    password=password), birth_date=birth_date, favorite_ball_game=favorite_ball_game)
        player.user.save()
        player.save()
        return player

    def validate_and_save(self, birth_date, favorite_ball_game, profile_picture=None):
        errors = []
        try:
            datetime.datetime.strptime(birth_date, '%Y-%m-%d').date()
            self.birth_date = birth_date
        except ValueError:
            errors.append("Invalid birth date format, Please use the format YYYY-MM-DD.")

        ball_games_names = [choice[0] for choice in BallGame.choices]
        if favorite_ball_game not in ball_games_names:
            errors.append("Invalid favorite ball game, Please select a valid option.")
        else:
            self.favorite_ball_game = favorite_ball_game

        if profile_picture:
            if not profile_picture.name.lower().endswith(('.png', '.jpeg', '.jpg')):
                errors.append("Invalid picture format, Please upload a JPEG or PNG image.")
            else:
                self.profile_pic.save(profile_picture.name, profile_picture, save=False)

        if errors:
            raise ValidationError("\n".join(errors))

        else:
            self.save()

    def is_event_time_available(self, desired_event_time):
        from game_event_player.models import GameEventPlayer
        TIME_LIMIT = 4
        start_time_limit = desired_event_time - timezone.timedelta(hours=TIME_LIMIT)
        end_time_limit = desired_event_time + timezone.timedelta(hours=TIME_LIMIT)
        conflicting_events = GameEventPlayer.objects.filter(player=self,
                                                            game_event__time__range=(start_time_limit,
                                                                                     end_time_limit))
        return not conflicting_events.exists()

meet_balls_app/views.py
from django.shortcuts import render, redirect
from datetime import datetime
from django.core.exceptions import ValidationError
from django.contrib.auth import authenticate, logout, login
from django.contrib import messages
from player.models import BallGame, Player
from django.contrib.auth.models import User
from player_rating.models import PlayerRating
from game_event_player.models import GameEventPlayer
from notification.models import Notification
from django.db.models import Count
from django.contrib.auth.decorators import login_required


def home(request):
    return render(request, 'meet_balls_app/home.html')


def notifications(request):
    notifications = Notification.objects.filter(player=request.user.player)

    context = {
        'notifications': notifications
    }

    return render(request, 'meet_balls_app/notifications.html', context)


def loginUser(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('home')
        else:
            error_message = "Invalid username or password."
            messages.error(request, error_message)
            return render(request, 'meet_balls_app/login.html')
    else:
        return render(request, 'meet_balls_app/login.html')


def logoutUser(request):
    logout(request)
    return redirect('home')


def registerUser(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        confirm_password = request.POST.get('confirm_password')
        birthdate = request.POST.get('birthdate')
        favorite_ball_game = request.POST.get('favorite_ball_game')
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')

        data = {
            'username': username,
            'password': password,
            'confirm_password': confirm_password,
            'birthdate': birthdate,
            'favorite_ball_game': favorite_ball_game,
            'first_name': first_name,
            'last_name': last_name,
        }
        errors = validate_register_form(data)
        if errors:
            for error in errors:
                messages.error(request, error)
            return render(request, 'meet_balls_app/register.html',
                          {'ball_games': BallGame.choices})
        else:
            try:
                Player.create(
                    username, password, birthdate, favorite_ball_game)
                messages.error(request, '')
                user = User.objects.get(username=username)
                user.first_name = first_name
                user.last_name = last_name
                user.save()
                return redirect('loginUser')
            except ValidationError as e:
                error_messages = e.messages[0].split("\n")
                for error in error_messages:
                    messages.error(request, error)
                    return render(request, "/meet_balls_app/register.html", {'ball_games': BallGame.choices})
    else:
        messages.error(request, '')
        return render(request, 'meet_balls_app/register.html', {'ball_games': BallGame.choices})


def validate_register_form(data):
    errors = []

    if not (data['username'] and data['password'] and
            data['confirm_password'] and data['birthdate'] and
            data['favorite_ball_game'] and data['first_name'] and data['last_name']):
        errors.append("All fields are required.")
    if data['password'] != data['confirm_password']:
        errors.append("Passwords do not match.")
    if User.objects.filter(username=data['username']).exists():
        errors.append("Username already exists.")
    if not any(data['favorite_ball_game'] in choice for choice in BallGame.choices):
        errors.append("Invalid ball game selection.")
    try:
        birthdate = datetime.strptime(data['birthdate'], '%Y-%m-%d').date()
        if birthdate >= datetime.now().date():
            errors.append("Birthdate must be in the past.")
    except ValueError:
        errors.append("Invalid birthdate format.")

    return errors


@login_required(login_url="/login/")
def profile(request, id):
    try:
        player = Player.objects.get(user=id)
    except Player.DoesNotExist:
        return render(request, 'meet_balls_app/profile.html', {})
    ratings = PlayerRating.objects.filter(player=player)

    game_counts = GameEventPlayer.objects.filter(player=player).values('game_event__ball_game').annotate(
        count=Count('game_event__ball_game'))
    game_history_data = {item['game_event__ball_game']: item['count'] for item in game_counts}

    return render(request, 'meet_balls_app/profile.html',
                  {'player': player, 'ratings': ratings, 'game_history_data': game_history_data, 'url_id': id})


@login_required(login_url="/login/")
def edit_profile(request):
    player = Player.objects.get(user=request.user.id)
    ratings = PlayerRating.objects.filter(player=player)
    if request.method == 'POST':
        birth_date = request.POST.get('birth_date')
        favorite_ball_game = request.POST.get('favorite_ball_game')
        profile_picture = request.FILES.get('profile_picture')
        try:
            player.validate_and_save(birth_date, favorite_ball_game, profile_picture)
            for rating in ratings:
                rating_value = request.POST.get(f"rating[{rating.id}]")
                rating.rating = int(rating_value)
                rating.save()
            return redirect('profile', id=player.user.id)
        except ValidationError as e:
            error_messages = e.messages[0].split("\n")
            for error in error_messages:
                messages.error(request, error)
            return redirect("edit profile")
    else:
        return render(request, 'meet_balls_app/edit_profile_form.html', {
            "player": player,
            "ratings": ratings,
            "ball_games": BallGame.choices})

meet_balls_app/templates/meet_balls_app/edit_profile_form.html
{% extends 'base.html' %}

{% block content %}
<div style="width: 40%; margin: 0 auto;">

  <h1>Edit Player Profile</h1>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}

    <div class="form-group">
      <label for="id_birth_date">Birth Date</label>
      <input type="date" class="form-control" id="id_birth_date" name="birth_date" value="{{ player.birth_date|date:'Y-m-d' }}">
    </div>

    <div class="form-group">
      <label for="id_favorite_ball_game">Favorite Ball Game</label>
      <select class="form-control" id="id_favorite_ball_game" name="favorite_ball_game">
        {% for ball_game in ball_games %}
          <option value="{{ ball_game.0 }}" {% if player.favorite_ball_game == ball_game.0 %}selected{% endif %}>{{ ball_game.0 }}</option>
        {% endfor %}
      </select>
    </div>

    <h2>Player Ratings</h2>
    {% for rating in ratings %}
      <div class="form-group">
        <label for="id_rating_{{ rating.id }}">Rating for {{ rating.ball_game }}</label>
        <input type="number" min="0" max="10" class="form-control" id="id_rating_{{ rating.id }}" name="rating[{{ rating.id }}]" value="{{ rating.rating }}" required>
      </div>
    {% endfor %}

  <div class="form-group mt-2">
      <label for="id_profile_picture">Profile Picture</label>
        <input type="file" class="form-control-file" id="id_profile_picture" name="profile_picture">
      <img src="{{ player.profile_pic.url }}" alt="Profile Picture" width="200" height="200" class="rounded-circle mt-3">
  </div>

    <button onclick="location.href='{% url 'profile' player.user.id %}'" class="round-button mt-3">Cancel</button>
    <button type="submit" class="round-button">Save Changes</button>
  </form>

  {% if messages %}
  <div class="row my-4">
    <div class="col">
      <div class="alert alert-danger" role="alert">
        <ul class="messages">
          {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
          {% endfor %}
        </ul>
      </div>
    </div>
  </div>
{% endif %}
</div>

{% endblock %}

meet_balls_app/templates/meet_balls_app/home.html
{% extends 'base.html'%} {%block content%}
<main>
  <h2>Welcome to MeetBalls</h2>
  <p>
    MeetBalls is an app that lets you schedule events to play with people near
    you. Whether you're into sports, games, or just want to hang out, MeetBalls
    makes it easy to find like-minded people to play with.
  </p>
  <p>With MeetBalls, you can:</p>
  <ul>
    <li>Schedule an event for a specific activity, location, date, and time</li>
    <li>
      Invite others to join your event and specify how many extra people you
      want to play with
    </li>
    <li>
      Chat with the other users in a group chat to coordinate and plan your
      event
    </li>
    <li>
      Browse and join other events that have been scheduled by other users
    </li>
  </ul>
</main>
{%endblock%}

meet_balls_app/templates/meet_balls_app/login.html
{% extends 'base.html'%}
{%block content%}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6 col-lg-4">
            <h2 class="text-center mb-4">Login</h2>
            <form method="post">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="username" class="form-label">Username:</label>
                    <input type="text" class="form-control" name="username" required>
                </div>
                <div class="mb-3">
                    <label for="password" class="form-label">Password:</label>
                    <input type="password" class="form-control" name="password" required>
                </div>
                <button type="submit" class="btn btn-primary">Login</button>
            </form>
            <p>Don't have an account? <a href="/register">Register</a> now.</p>
            {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
                    {% endfor %}
            </ul>
            
            {% endif %}
        </div>
    </div>
</div>
{%endblock%}

meet_balls_app/templates/meet_balls_app/notifications.html
{% extends 'base.html' %}

{% block content %}
    <h1>Notifications</h1>

    {% if notifications %}
        {% for notification in notifications %}
            <div class="notification {% if notification.is_read %}seen{% else %}unseen{% endif %}">
                <div class="notification-header">
                    <div class="notification-title">
                        {{ notification.notification_type }}
                    </div>
                    <div class="notification-time">
                        {{ notification.sent_time }}
                    </div>
                </div>
                <button class="notification-button" onclick="toggleNotification(this)">
                    View Details
                </button>
                <div class="notification-details">
                    <p>{{ notification.message }}</p>
                    <p>Time Received: {{ notification.sent_time }}</p>
                </div>
            </div>
        {% endfor %}
    {% else %}
        <h5>No notifications</h5>
    {% endif %}
{% endblock %}



{% block scripts %}
    <script>
        function toggleNotification(button) {
            var details = button.nextElementSibling;
            details.classList.toggle("show");
        }
    </script>
{% endblock %}

meet_balls_app/templates/meet_balls_app/profile.html
{% extends 'base.html' %} {% block content %}
{% if player %}
    <div class="text-center">
    <img src="{{ player.profile_pic.url }}" alt="Profile Picture" width="200" height="200" class="rounded-circle">
    <h2>Profile Information</h2>
    <p>Name: {{ player.user.first_name }} {{ player.user.last_name }}</p>
    <p>Date of Birth: {{ player.birth_date }}</p>
    <p>Favorite Ball Game: {{ player.favorite_ball_game }}</p>
  </div>
<h2 class="text-center">Player Ratings</h2>
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-5">
        <table class="table table-striped table-bordered">
        <thead class="thead-dark">
          <tr>
            <th>Ball Game</th>
            <th>Rating</th>
          </tr>
        </thead>
        <tbody>
          {% for rating in ratings %}
          <tr>
            <td>{{ rating.ball_game }}</td>
            <td>{{ rating.rating }}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>

<div class="text-center">
  {% if user.id|stringformat:"s" == url_id %}
    <div>
      <button onclick="location.href='{% url 'edit profile' %}'" class="round-button">Edit Profile</button>
    </div>
  {% endif %}
</div>

<h2 class="text-center">Game History</h2>
<div>
  <canvas id="gameHistoryChart"></canvas>
</div>
    {% block scripts %}
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script>
  document.addEventListener("DOMContentLoaded", function() {
    var gameHistoryData = {
      labels: [
        {% for ball_game, count in game_history_data.items %}
          "{{ ball_game }}",
        {% endfor %}
      ],
      datasets: [{
        data: [
          {% for ball_game, count in game_history_data.items %}
            {{ count }},
          {% endfor %}
        ],
        backgroundColor: [
          '#EDD785',
          '#524346',
          '#a7898e',
          '#9389a7',
          '#89a7a2',
          '#899aa7',
          '#e3dbd8',
          '#b9a1a5',
          '#e5dcdd',
        ],
        borderWidth: 1
      }]
    };

    var gameHistoryChart = new Chart(document.getElementById("gameHistoryChart"), {
      type: 'pie',
      data: gameHistoryData,
      options: {
        responsive: true,
        maintainAspectRatio: false,
        plugins: {
          legend: {
            position: 'bottom',
          },
        },
        layout: {
          padding: {
            left: 0,
            right: 0,
            top: 20,
            bottom: 20,
          },
        },
      },
    });
  });
</script>
{% endblock %}
{% else %}
    <div class="text-center">
      <h2>Player Not Found</h2>
      <p>The requested player does not exist.</p>
    </div>
  {% endif %}
{% endblock %}

meet_balls_app/templates/meet_balls_app/register.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6 col-lg-4">
            <h2 class="text-center mb-4">Register</h2>
            <form method="post">
                {% csrf_token %}
                <div class="mb-2">
                    <label for="first_name" class="form-label">First Name:</label>
                    <input type="text" class="form-control" name="first_name" required>
                </div>
                <div class="mb-3">
                    <label for="last_name" class="form-label">Last Name:</label>
                    <input type="text" class="form-control" name="last_name" required>
                </div>
                <div class="mb-3">
                    <label for="username" class="form-label">Username:</label>
                    <input type="text" class="form-control" name="username" required>
                </div>
                <div class="mb-3">
                    <label for="password" class="form-label">Password:</label>
                    <input type="password" class="form-control" name="password" required>
                </div>
                <div class="mb-3">
                    <label for="confirm_password" class="form-label">Confirm Password:</label>
                    <input type="password" class="form-control" name="confirm_password" required>
                </div>
                <div class="mb-3">
                    <label for="birthdate" class="form-label">Birthdate:</label>
                    <input type="date" class="form-control" name="birthdate" required>
                </div>
                <div class="mb-3">
                    <label for="favorite_ball_game" class="form-label">Favorite Ball Game:</label>
                    <select class="form-select" name="favorite_ball_game" required>
                        {% for ball_game in ball_games %}
                        <option value="{{ ball_game.0 }}">{{ ball_game.1 }}</option>
                        {% endfor %}
                    </select>
                </div>
                <button type="submit" class="btn btn-primary">Register</button>
            </form>
            <p>Already have an account? <a href="{% url 'loginUser' %}">Login</a>.</p>
            {% if messages %}
            <div class="row my-4">
                <div class="col-12">
                    <div class="alert alert-danger" role="alert">
                        <ul class="messages">
                            {% for message in messages %}
                            <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}